export EDU_DOTFILES="$HOME/projects/dotfiles"
export EDITOR="nvim"

# ohmyzsh
plugins=(git history z zsh-syntax-highlighting zsh-autosuggestions zsh-completions colorize colored-man-pages aws zsh-history-substring-search)

source $EDU_DOTFILES/bash/tmux

alias ccd="claude"
